# -*- coding: utf-8 -*-
"""fuzzy_jf

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BpfCQOiRfnVF8R8bTHEzmik5DlUEde_k
"""

#!pip install scikit-fuzzy

import skfuzzy as fuzz
from skfuzzy import control as ctrl
import numpy as np

comida = ctrl.Antecedent(np.arange(0,11,1), 'comida')
servicio = ctrl.Antecedent(np.arange(0,11,1), 'servicio')
propina = ctrl.Consequent(np.arange(0,11,1), 'propina')

propina

"""## Funcion de membresia o pertenencia para las entradas"""

comida.automf(3) # 3 = numero de conjuntos difusos
servicio.automf(3)

"""##Funciones de membresia para la salida"""

propina['baja'] = fuzz.trimf(propina.universe, [0,0,4])
propina['media'] = fuzz.trimf(propina.universe, [0,4,7])
propina['alta'] = fuzz.trapmf(propina.universe, [4,7,10,10])

comida.view()
servicio.view()
propina["media"].view()

"""## Crear reglas"""

rule1 = ctrl.Rule(servicio['poor'] or comida['poor'], propina['baja'])
rule2 = ctrl.Rule(comida['average'] or servicio['average'], propina['media'])
rule3 = ctrl.Rule(comida['good'] or servicio['good'], propina['alta'])
rule1.view()

tipping_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])
FIS = ctrl.ControlSystemSimulation(tipping_ctrl)

FIS.input['servicio'] = 2
FIS.input['comida'] = 5
FIS.compute()
print(FIS.output['propina'])
propina.view(sim=FIS)